config:
  title: "Three channel image version"

data:
  name: 'OD_SIIM'
  input: 'C:\Users\Admin\Git\SIIM\train'
  df:
    path: 'input/id_s.csv'
  collate_name: 'OD_collate'
  params:
    val_fold: 4

model:
  name: 'FasterRCNNDetector'

train:
  dir:
  batch_size: 1
  num_epochs: 20
  gradient_clipping:
    params:
      clip_value: 1.0


loss:
  name: ''

metric:
  name: "image_precision"
  params:
    iou_thresholds: [0.4, 0.5, 0.6]
    form: 'pascal_voc'

optimiser:
  name: 'sgd'
  params:
    lr: 0.008

scheduler:
  name: 'step'
  params:
    step_size: 5

transform:
  name: 'transform'
  params:
    reshape_size: 800

output:
  dir: 'out/'

